apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

namespace: prod
commonLabels:
  env: prod

# resources:
#   - namespace.yaml

patches:
  - patch-deploy.yaml
  - patch-svc.yaml

images:
  - name: customers
    newName: us.icr.io/devops_customers/devops-customers:1.0
    newTag: "21"
