apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
      # https://cloud.ibm.com/docs/containers?topic=containers-registry#other
      - name: all-icr-io
